# Module 6 Confusion Matrix

- Use scikit-learn APIs.

### True labels

In [1]:
true_labels = ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A','A', 'A', 'B', 'B', 'B','B', 'B', 'B', 'B', 'B','B', 'B']

In [2]:
true_labels

['A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B']

In [3]:
len(true_labels)

20

### Predicted labels by a classifier

In [4]:
predicted_labels = ['A', 'B', 'A', 'B', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'B']

In [6]:
predicted_labels

['A',
 'B',
 'A',
 'B',
 'B',
 'A',
 'A',
 'A',
 'A',
 'B',
 'B',
 'B',
 'B',
 'A',
 'A',
 'A',
 'B',
 'B',
 'B',
 'B']

In [5]:
len(predicted_labels)

20

In [7]:
from sklearn.metrics import confusion_matrix

### Show confusion matrix

In [8]:
confusion_matrix(true_labels, predicted_labels)

array([[6, 4],
       [3, 7]], dtype=int64)

In [9]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

### Show precision value

In [10]:
precision_score(true_labels, predicted_labels, labels=['A', 'B'], pos_label='A')

0.6666666666666666

### Show recall value

In [11]:
recall_score(true_labels, predicted_labels, labels=['A', 'B'], pos_label='A')

0.6

### Show f1 value

In [12]:
f1_score(true_labels, predicted_labels, labels=['A', 'B'], pos_label='A')

0.631578947368421

### Show accuracy value

In [13]:
print(accuracy_score(true_labels, predicted_labels))

0.65


### Use train_test_split to divide data into training data and test data.

In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

### Create some random data and labels.

In [15]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [16]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
y

range(0, 5)

In [18]:
list(y)

[0, 1, 2, 3, 4]

### Use 40% of the data as test; 

- assign **random_state** number so that this can be repeated.

In [19]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.4, random_state=42)

### Traing data

- 3 data points

In [20]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

### Training data labels

In [21]:
y_train

[2, 0, 3]

### Test data

- 2 data points

In [22]:
X_test

array([[2, 3],
       [8, 9]])

### Test data labels

In [23]:
y_test

[1, 4]