# Purpose of the Notebook

This Jupyter Notebook is to review the concepts of Python that are relavant to the course. Topics covered will stated at the beginning of each video.  This sample code is from Module 3 of the course.

# Videos 
Topics covered:
- Lists
- Dictionaries
- Set
- Tuples
- Numpy arrays

**Notes:**
- **append()** - used to add an element to the end of the list
- **insert()** - to insert an element at a specific index in the list
- **pop** - to remove the element from a list

In [1]:
# List example
l = [6, 7,2,1,4]

In [2]:
print(l)      # print the contents of the list.

[6, 7, 2, 1, 4]


In [3]:
l             # another way to print the list in a notebook.

[6, 7, 2, 1, 4]

In [4]:
# add an element to the end of the list
l.append(54)
print(l)

[6, 7, 2, 1, 4, 54]


In [5]:
# insert an element at a specific index
l.insert(0 , 28)                            # will insert a new element at position zero
print(l)

[28, 6, 7, 2, 1, 4, 54]


In [6]:
# remove an element from the list.
l.pop(3)                                    # will remove an element at the given position and return the value

2

In [7]:
print(l)

[28, 6, 7, 1, 4, 54]


### Dictionary Demo
- **.keys()** - will return all the keys in the dictionary.
- When adding a new value to the dictionary make sure the key is **unique**.  Cannot have the same key values.
- To update a dictionary supply the key and the new value for the key.

In [9]:
dict = {'John':14, 'Tom': 18, 'Susan':17, 'Helen':19}

In [10]:
len(dict)              # will return the length of the dictionary

4

In [11]:
dict.keys()             # will return the keys in the dictionary

dict_keys(['John', 'Tom', 'Susan', 'Helen'])

In [12]:
# processing a dictionary using a for loop
for key in dict.keys():
    print(key)                         # prints the key
    print(dict[key])                   # prints the value
    print('-----')

John
14
-----
Tom
18
-----
Susan
17
-----
Helen
19
-----


In [13]:
# to add a new value to the dictionary
dict['Andy'] = 13
dict

{'John': 14, 'Tom': 18, 'Susan': 17, 'Helen': 19, 'Andy': 13}

In [14]:
# to update a key and its value
dict['John'] = 24
dict

{'John': 24, 'Tom': 18, 'Susan': 17, 'Helen': 19, 'Andy': 13}

### Sets Demo
- **set()** - creates a set from the given values

In [15]:
set1 = set([13, 5, 6, 8])
set2 = set([2, 4, 6, 8])

In [16]:
print(set1)
print(set2)

{8, 5, 13, 6}
{8, 2, 4, 6}


### Union Demo
- **union()** - joins two sets together.
- If there are duplicates only one element will be kept in the new union.

In [17]:
set1.union(set2)

{2, 4, 5, 6, 8, 13}

In [18]:
# intersection example
set1.intersection(set2)

{6, 8}

In [19]:
# difference example
set1.difference(set2)

{5, 13}

In [20]:
set2.difference(set1)

{2, 4}

### Tuples Demo
- tuples are immutable 

In [21]:
tuple = (3, 4, 2)
type(tuple)

tuple

In [22]:
# to print an element
tuple[0]

3

In [23]:
# try to change a value example
tuple[0] = 33

TypeError: 'tuple' object does not support item assignment

### Numpy Array Demp
- Will need to import numpy using the following:
   - import numpy as np
- A Numpy array does **not** allow different data types. All elements must be of the same tyepe.

In [24]:
import numpy as np

a = np.array(l)
print(a)

[28  6  7  1  4 54]


In [25]:
type(a)

numpy.ndarray

In [26]:
a

array([28,  6,  7,  1,  4, 54])

In [27]:
# the list from previous cells
l

[28, 6, 7, 1, 4, 54]

In [28]:
l.append('me')
l

[28, 6, 7, 1, 4, 54, 'me']

In [29]:
# change the first element of a integer numpy array to a string example
a[0] = 'me'

ValueError: invalid literal for int() with base 10: 'me'

# Section Covers

Topics covered:
- Pandas 
- Pandas Series
- Pandas DataFrame

**Notes:**
- need to import
  - import pandas as pd
- obj1.**index** - will show the ranges of the indexes for the Series.
- obj1.**values** - will display the values in the series
- The power of using Series is that they can be assigned labels/ names or string labels as indices for the series.
- When using a dictionary to create a Series the keys of the dictionary will be used for the labels of the Series.

In [30]:
from pandas import Series, DataFrame

In [31]:
# creating a Series object from a list of integers.
obj1 = Series([4, 7, -5, 3])

In [32]:
type(obj1)

pandas.core.series.Series

In [33]:
obj1

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj1[2]         # to access an element by its index

-5

In [35]:
obj1.index     # will show the range of the indexes for the series

RangeIndex(start=0, stop=4, step=1)

In [36]:
obj1.values   # will display the values of the series

array([ 4,  7, -5,  3], dtype=int64)

In [37]:
# assigning index names to the series
obj1.index = ['d','b','a','c']
obj1

d    4
b    7
a   -5
c    3
dtype: int64

In [38]:
# to access the content of a series using the label
obj1['a']

-5

In [39]:
# to access the content of a series using the index
obj1[2]

C:\Users\ntcrw\AppData\Local\Temp\ipykernel_19112\1388806891.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj1[2]


-5

In [40]:
# assigning index names at the same time as creating the Series
obj2 = Series([4, 7, -5, 3], index=['d','p','a','h'])
obj2

d    4
p    7
a   -5
h    3
dtype: int64

In [41]:
# create a series out of a dictionary
sdata = {'Ohio': 35000, 'Texas': 71000 ,'Oregon': 16000,'Utah': 5000}

In [42]:
obj4 = Series(sdata)
obj4

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [43]:
obj4['Utah']          # to access the elements in the series using the labels.

5000

In [44]:
# to access using number index
obj4[3]

C:\Users\ntcrw\AppData\Local\Temp\ipykernel_19112\3741740087.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj4[3]


5000

### Creation of a DataFrame object

**Notes**:
- Each in a dictionary will be the name of the column in the dataframe.
- Adding one more pair of [] will return a DataFrame.
- **.index** - to the range of the indexes of the dataframe
- **.columns** - to view the columns of the dataframe
- **.head()** - to view a specific number of the top rows, default is 5
- **.tail()** - to view a specific number of the bottom rows, default is 5
- **.iloc[]** - to access data via the index in the dataframe 
- **.loc[]** - to access data via the label index in the dataframe


In [45]:
# Creates a dictionary
data = {'state': ['Ohio','Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year':[2000, 2001, 2002, 2001, 2002], 'pop':[1.5, 1.7, 3.6
                                                                                                             ,2.4, 2.9]}

In [46]:
type(data)

dict

In [47]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [48]:
# Create a dataframe out of the dictionary (data)
df1 = DataFrame(data)

df1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [49]:
# to view the indexes of the DataFrame
df1.index

RangeIndex(start=0, stop=5, step=1)

In [50]:
# to view the columns of the dataframe
df1.columns

Index(['state', 'year', 'pop'], dtype='object')

In [51]:
# to view a specific number of top rows
df1.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [52]:
# to view a specific number of bottom rows
df1.tail(3)

state  year  pop
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [53]:
# to assign own lables to the rows 
df1.index = ['one','two','three','four','five']
df1

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4
five   Nevada  2002  2.9

In [54]:
# to access data from the dataframe
df1.iloc[0]                              # will get the first column of the dataframe

state    Ohio
year     2000
pop       1.5
Name: one, dtype: object

In [55]:
# Checking the type
type(df1.iloc[0])

pandas.core.series.Series

In [56]:
# adding one more pair of []
df1.iloc[[0]]

state  year  pop
one  Ohio  2000  1.5

In [57]:
type(df1.iloc[[0]])

pandas.core.frame.DataFrame

In [58]:
# to access data from the dataframe using the label index
df1.loc['one'] 

state    Ohio
year     2000
pop       1.5
Name: one, dtype: object

In [59]:
# adding one more pair of []
df1.loc[['one']]

state  year  pop
one  Ohio  2000  1.5

In [60]:
type(df1.loc[['one']])

pandas.core.frame.DataFrame

In [61]:
# to retrieve a specific column
df1['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [62]:
type(df1['state'])

pandas.core.series.Series

In [63]:
df1

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4
five   Nevada  2002  2.9

In [64]:
df1[['state']]         # returns a dataframe not a Series

state
one      Ohio
two      Ohio
three    Ohio
four   Nevada
five   Nevada

In [65]:
# to access a particular cell
df1.iloc[0, 2]                          #  gives the first row and the third column

1.5

In [66]:
# using label indexe
df1.loc['one', 'pop']                  #  gives the first row and the third column

1.5

In [67]:
# For a range or a segment (a slice of the dataframe)
df1.iloc[0:2, 0:2]

state  year
one  Ohio  2000
two  Ohio  2001

In [68]:
# to display values not in a fixed range use the labels
df1.loc[['one', 'five'], ['state','pop']]

state  pop
one     Ohio  1.5
five  Nevada  2.9

In [69]:
df1.iloc[[0,4], [0, 2]]

state  pop
one     Ohio  1.5
five  Nevada  2.9

# Section Covers

Topics covered:
- Data transfer between structures
-

**Notes:**
- .

In [70]:
l = [5, 2, 3, 11, 5, 6, 3]

In [71]:
# creating a set from the list
s = set(l)
s

{2, 3, 5, 6, 11}

In [72]:
# convert set to a list
l_2 = list(s)
l_2

[2, 3, 5, 6, 11]

In [73]:
l = [4, 13, 21, 56]
se1 = Series(l)
print(type(l))
print(type(se1))
print(se1)

<class 'list'>
<class 'pandas.core.series.Series'>
0     4
1    13
2    21
3    56
dtype: int64


In [74]:
df1

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4
five   Nevada  2002  2.9

In [75]:
# to a column to a list Note:
df1['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [76]:
# Note: Converting you will lose all the labels
list_1 = list(df1['state'])
list_1

['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada']

In [77]:
# to keep the label create a dictionary the labels will be come the keys
df1['year'].to_dict()

{'one': 2000, 'two': 2001, 'three': 2002, 'four': 2001, 'five': 2002}

In [78]:
# to keep the label create a dictionary the labels will become the keys
df1['state'].to_dict()

{'one': 'Ohio',
 'two': 'Ohio',
 'three': 'Ohio',
 'four': 'Nevada',
 'five': 'Nevada'}

In [79]:
# will create row one as a dictionary
df1.loc['one'].to_dict()

{'state': 'Ohio', 'year': 2000, 'pop': 1.5}