# Module 14 MLP (Using PyTorch)

- uses pytorch
- uses iris.csv file

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:\\Jupyter_Notebooks\\CS654ML_DM\\Data\\iris.csv")

In [3]:
df

sepalLength  sepalWidth  petalLength  petalWidth         species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

### Convert labels

- convert labels into numerical values
- uses **map()** to map to a numerical value

In [4]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
df['species'] = df['species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

In [6]:
df

sepalLength  sepalWidth  petalLength  petalWidth  species
0            5.1         3.5          1.4         0.2        0
1            4.9         3.0          1.4         0.2        0
2            4.7         3.2          1.3         0.2        0
3            4.6         3.1          1.5         0.2        0
4            5.0         3.6          1.4         0.2        0
..           ...         ...          ...         ...      ...
145          6.7         3.0          5.2         2.3        2
146          6.3         2.5          5.0         1.9        2
147          6.5         3.0          5.2         2.0        2
148          6.2         3.4          5.4         2.3        2
149          5.9         3.0          5.1         1.8        2

[150 rows x 5 columns]

### Training data 

- get the training data from the feature/attribute columns
- will contain all columns except 'species'

In [7]:
X = df.drop(['species'], axis=1).values

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y = df['species'].values

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split

### Split the data into training and testing sets

- uses 20% for the test size

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Convert the data

-  conver the data into a tensor for use with pytorch

In [13]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

### Description pytorch variables

- batch_no: size of the traing set divided by the batch size
- cols: the number of columns/features/attributes in the training set  

In [14]:
batch_size = 60
num_epochs = 1000
learning_rate = 0.01
size_hidden = 128

batch_no = len(X_train) // batch_size
cols = X_train.shape[1]
classes = len(np.unique(y_train))

### Verify the above

In [15]:
print(batch_no)
print(cols)
print(classes)

2
4
3


### Define the neural network

In [16]:
class MyNeuralNetwork(nn.Module):

    def __init__(self, cols, size_hidden, classes):

        super(MyNeuralNetwork, self).__init__()

        self.fc1 = nn.Linear(cols, size_hidden)
        
        self.fc2 = nn.Linear(size_hidden, classes)

    def forward(self, x):

        x = self.fc1(x)
        x = F.dropout(x, p=0.1)
        x = F.relu(x)
        x = self.fc2(x)

        return F.softmax(x, dim=1)   

### Construct the model

In [17]:
input_dim = 4
output_dim = 3

model = MyNeuralNetwork(input_dim, size_hidden, output_dim)

### Define the optimization function

- Adam is a specific type of gradient decent with good performance

In [18]:
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

criterion = nn.CrossEntropyLoss()

In [19]:
import numpy as np

num_epochs = 1000

train_losses = np.zeros(num_epochs)

### Training

In [20]:
for epoch in range(num_epochs):

    # clear out the gradients
    optimizer.zero_grad()

    # forward feed
    output_train = model(X_train)

    # calculate the loss
    loss_train = criterion(output_train, y_train)

    # backward propagation: calculate gradients
    loss_train.backward()

    # update the weights
    optimizer.step()

    train_losses[epoch] = loss_train.item()

    if(epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1}/ {num_epochs}, Train Loss: {loss_train.item(): .4f}")    

Epoch 20/ 1000, Train Loss:  0.7279
Epoch 40/ 1000, Train Loss:  0.6295
Epoch 60/ 1000, Train Loss:  0.6054
Epoch 80/ 1000, Train Loss:  0.5916
Epoch 100/ 1000, Train Loss:  0.5898
Epoch 120/ 1000, Train Loss:  0.5858
Epoch 140/ 1000, Train Loss:  0.5831
Epoch 160/ 1000, Train Loss:  0.5809
Epoch 180/ 1000, Train Loss:  0.5797
Epoch 200/ 1000, Train Loss:  0.5811
Epoch 220/ 1000, Train Loss:  0.5808
Epoch 240/ 1000, Train Loss:  0.5816
Epoch 260/ 1000, Train Loss:  0.5762
Epoch 280/ 1000, Train Loss:  0.5745
Epoch 300/ 1000, Train Loss:  0.5783
Epoch 320/ 1000, Train Loss:  0.5742
Epoch 340/ 1000, Train Loss:  0.5737
Epoch 360/ 1000, Train Loss:  0.5752
Epoch 380/ 1000, Train Loss:  0.5790
Epoch 400/ 1000, Train Loss:  0.5731
Epoch 420/ 1000, Train Loss:  0.5735
Epoch 440/ 1000, Train Loss:  0.5731
Epoch 460/ 1000, Train Loss:  0.5784
Epoch 480/ 1000, Train Loss:  0.5758
Epoch 500/ 1000, Train Loss:  0.5750
Epoch 520/ 1000, Train Loss:  0.5734
Epoch 540/ 1000, Train Loss:  0.5811
Epoch

### Do the predictions on both training data and testing data

In [21]:
predictions_train = []
predictions_test = []

with torch.no_grad():
    
    predictions_train = model(X_train)
    predictions_test = model(X_test) 

In [22]:
predictions_train

tensor([[1.0000e+00, 1.0369e-07, 1.8803e-41],
        [1.0000e+00, 4.5139e-11, 1.7260e-41],
        [9.5748e-06, 9.9999e-01, 5.2048e-09],
        [1.0000e+00, 1.8863e-07, 1.5795e-33],
        [1.0000e+00, 3.2752e-08, 4.8694e-35],
        [7.1693e-12, 5.6380e-05, 9.9994e-01],
        [1.0804e-04, 9.9989e-01, 4.0637e-08],
        [1.0000e+00, 1.2779e-08, 3.3870e-38],
        [1.0000e+00, 5.6755e-09, 1.4949e-34],
        [1.0000e+00, 1.4499e-10, 1.4013e-45],
        [2.2959e-12, 1.0968e-05, 9.9999e-01],
        [8.7571e-05, 9.9991e-01, 6.3348e-06],
        [1.2557e-05, 9.9998e-01, 7.5908e-06],
        [1.0000e+00, 1.4726e-09, 9.2920e-42],
        [1.0000e+00, 1.0037e-09, 1.3583e-40],
        [6.6456e-05, 9.9993e-01, 5.6903e-09],
        [1.8367e-08, 1.2161e-01, 8.7839e-01],
        [8.6905e-11, 4.8317e-04, 9.9952e-01],
        [3.6825e-06, 1.0000e+00, 3.9417e-08],
        [4.6637e-14, 7.0397e-06, 9.9999e-01],
        [2.8601e-04, 9.9971e-01, 1.1945e-06],
        [1.0348e-16, 2.1231e-08, 1

In [23]:
y_train

tensor([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0,
        2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1,
        0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0,
        0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1,
        2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

### Output the maximum probability

- will output the maximum propbability from **predictions_train**

In [24]:
final_pred = []

for i in range(len(predictions_train)):

    final_pred.append(np.argmax(predictions_train[i]))

### Do the final label decision on training data predictions

In [25]:
final_pred = []

for i in range(len(predictions_train)):

    final_pred.append(np.argmax(predictions_train[i]))

final_pred = np.array(final_pred)

In [26]:
final_pred

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2], dtype=int64)

### Accuracy of the training data predictions

In [27]:
matched =0

for i in range(len(y_train)):
    
    if final_pred[i] == y_train[i]:
        matched = matched + 1

print(matched / len( y_train))

0.9833333333333333


### Check the returned results on test data predictions

In [28]:
predictions_test

tensor([[6.2759e-06, 9.9977e-01, 2.2116e-04],
        [1.0000e+00, 4.6498e-06, 8.6232e-31],
        [1.6940e-18, 1.8036e-11, 1.0000e+00],
        [2.5893e-05, 9.9970e-01, 2.7102e-04],
        [1.0456e-06, 9.9997e-01, 2.8038e-05],
        [9.9938e-01, 6.2211e-04, 3.1531e-33],
        [1.1585e-03, 9.9884e-01, 4.6438e-11],
        [4.4196e-10, 2.3077e-03, 9.9769e-01],
        [4.4591e-08, 3.2244e-01, 6.7756e-01],
        [4.4157e-05, 9.9996e-01, 1.0339e-08],
        [9.3306e-09, 3.2745e-02, 9.6726e-01],
        [1.0000e+00, 2.4435e-07, 4.5108e-32],
        [1.0000e+00, 5.6682e-07, 2.6862e-35],
        [1.0000e+00, 2.8010e-07, 5.7004e-33],
        [1.0000e+00, 2.1853e-09, 2.9747e-40],
        [3.2141e-06, 9.9996e-01, 3.9939e-05],
        [8.6107e-15, 2.2510e-07, 1.0000e+00],
        [2.0530e-05, 9.9998e-01, 6.1332e-08],
        [1.8755e-04, 9.9412e-01, 5.6886e-03],
        [3.4339e-15, 2.6945e-07, 1.0000e+00],
        [1.0000e+00, 1.3446e-07, 3.2751e-32],
        [4.0285e-07, 2.3381e-01, 7

In [29]:
y_test

tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
        2, 2, 2, 2, 0, 0])

In [30]:
final_pred = []

for i in range(len(predictions_test)):

    final_pred.append(np.argmax(predictions_test[i]))

final_pred = np.array(final_pred)

In [31]:
final_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

### Accuracy of the test data predictions

In [32]:
matched =0

for i in range(len(y_test)):
    
    if final_pred[i] == y_test[i]:
        matched = matched + 1

print(matched / len( y_test))

0.9666666666666667
